# Generated by Django 3.2 on 2023-06-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobId', models.CharField(max_length=30)),
                ('messageId', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('imageURL', models.CharField(max_length=200)),
            ],
        ),
    ]
